### PR TITLE
Bump deps

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Review by chilagrow — DISMISSED** [review]

**Comment by chilagrow** [comment]
Just saw the test failing, has anything changed which cased this?

```
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -15,4 +15,3 @@
            	            	   },
            	            	-  (string) (len=12) "Test project": (graphql.Fields) (len=2) {
            	            	-   (string) (len=4) "Size": (string) (len=1) "S",
            	            	+  (string) (len=12) "Test project": (graphql.Fields) (len=1) {
            	            	    (string) (len=6) "Status": (string) (len=4) "Done"
            	Test:       	TestPullRequest/ProjectV2
```

**Review by w84thesun — DISMISSED** [review]

**Review by noisersup — CHANGES_REQUESTED** [review]
Tests are failing, I belive that github changed something in graphql api?

**Comment by AlekSi** [comment]
It will be fixed by #115

**Review by rumyantseva — APPROVED** [review]
LGTM

**Review by noisersup — APPROVED** [review]

**Pull request merged**
